import 'dart:io';

import 'package:path/path.dart' as path;

import '../config.dart';
import '../utils.dart';

/// Generator for barrel (export) files
///
/// Scans feature directories and generates Dart barrel files
/// that export all public-facing files, keeping imports clean
/// and organized.
class BarrelGenerator {
  BarrelGenerator(this.config);
  final YoConfig config;

  /// Generate barrel files for a specific feature or all features
  void generate({String? feature, bool force = false}) {
    if (feature != null) {
      _generateForFeature(feature, force: force);
    } else {
      _generateForAllFeatures(force: force);
      _generateCoreBarrel(force: force);
    }
  }

  void _generateCoreBarrel({bool force = false}) {
    Console.info('Generating core barrel files...');

    final corePath = config.corePath;
    if (!Directory(corePath).existsSync()) return;

    final coreSubdirs =
        Directory(corePath).listSync().whereType<Directory>().toList();

    for (final dir in coreSubdirs) {
      _generateBarrelForDirectory(dir.path, force: force);
    }

    // Generate main core barrel
    final coreExports = StringBuffer()
      ..writeln('// Core barrel file - auto-generated by yo.dart')
      ..writeln('// DO NOT MODIFY BY HAND')
      ..writeln();

    for (final dir in coreSubdirs) {
      final dirName = path.basename(dir.path);
      final barrelFile = path.join(dir.path, '$dirName.dart');
      if (File(barrelFile).existsSync() || _hasDartFiles(dir.path)) {
        coreExports.writeln("export '$dirName/$dirName.dart';");
      }
    }

    final coreBarrelPath = path.join(corePath, 'core.dart');
    _writeBarrel(coreBarrelPath, coreExports.toString(), force: force);
  }

  void _generateBarrelForDirectory(String dirPath, {bool force = false}) {
    final dartFiles = Directory(dirPath)
        .listSync()
        .whereType<File>()
        .where(
          (f) =>
              f.path.endsWith('.dart') &&
              !path.basename(f.path).startsWith('_'),
        )
        .toList()
      ..sort((a, b) => a.path.compareTo(b.path));

    if (dartFiles.isEmpty) return;

    final dirName = path.basename(dirPath);
    final barrelPath = path.join(dirPath, '$dirName.dart');

    final buffer = StringBuffer()
      ..writeln('// Barrel file - auto-generated by yo.dart')
      ..writeln('// DO NOT MODIFY BY HAND')
      ..writeln();

    for (final file in dartFiles) {
      final fileName = path.basename(file.path);
      // Don't export the barrel file itself
      if (fileName == '$dirName.dart') continue;
      buffer.writeln("export '$fileName';");
    }

    _writeBarrel(barrelPath, buffer.toString(), force: force);
  }

  void _generateFeatureBarrel(
    String featurePath,
    String featureName, {
    bool force = false,
  }) {
    final buffer = StringBuffer()
      ..writeln('// Feature barrel file - auto-generated by yo.dart')
      ..writeln('// Feature: $featureName')
      ..writeln('// DO NOT MODIFY BY HAND')
      ..writeln();

    // Export presentation layer
    final presentationPath = path.join(featurePath, 'presentation');
    if (Directory(presentationPath).existsSync()) {
      _addExportsFromLayer(buffer, presentationPath, 'presentation');
    }

    // Export domain layer
    final domainPath = path.join(featurePath, 'domain');
    if (Directory(domainPath).existsSync()) {
      _addExportsFromLayer(buffer, domainPath, 'domain');
    }

    // Generate the feature barrel file
    final barrelPath = path.join(featurePath, '$featureName.dart');
    _writeBarrel(barrelPath, buffer.toString(), force: force);
  }

  void _generateForAllFeatures({bool force = false}) {
    Console.header('Generating Barrel Files');

    final featuresPath = config.featuresPath;
    if (!Directory(featuresPath).existsSync()) {
      Console.warning('No features directory found.');
      return;
    }

    final featureDirs =
        Directory(featuresPath).listSync().whereType<Directory>().toList();

    for (final dir in featureDirs) {
      final featureName = path.basename(dir.path);
      _generateForFeature(featureName, force: force);
    }

    // Generate features barrel file
    final featuresBuffer = StringBuffer()
      ..writeln('// Features barrel file - auto-generated by yo.dart')
      ..writeln('// DO NOT MODIFY BY HAND')
      ..writeln();

    for (final dir in featureDirs) {
      final featureName = path.basename(dir.path);
      featuresBuffer.writeln("export '$featureName/$featureName.dart';");
    }

    final featuresBarrelPath = path.join(featuresPath, 'features.dart');
    _writeBarrel(featuresBarrelPath, featuresBuffer.toString(), force: force);

    Console.success('Barrel files generated successfully.');
  }

  void _generateForFeature(String featureName, {bool force = false}) {
    final featurePath = config.featurePath(featureName);
    if (!Directory(featurePath).existsSync()) {
      Console.error('Feature "$featureName" does not exist.');
      return;
    }

    Console.info('Generating barrel files for feature: $featureName');

    // Generate barrel files for each layer subdirectory
    final layers = ['presentation', 'domain', 'data'];
    for (final layer in layers) {
      final layerPath = path.join(featurePath, layer);
      if (!Directory(layerPath).existsSync()) continue;

      final subdirs =
          Directory(layerPath).listSync().whereType<Directory>().toList();

      for (final dir in subdirs) {
        _generateBarrelForDirectory(dir.path, force: force);
      }
    }

    // Generate feature-level barrel file
    _generateFeatureBarrel(featurePath, featureName, force: force);
  }

  bool _hasDartFiles(String dirPath) => Directory(dirPath)
      .listSync(recursive: true)
      .whereType<File>()
      .any((f) => f.path.endsWith('.dart'));

  void _addExportsFromLayer(
    StringBuffer buffer,
    String layerPath,
    String layerName,
  ) {
    final subdirs = Directory(layerPath)
        .listSync()
        .whereType<Directory>()
        .toList()
      ..sort((a, b) => a.path.compareTo(b.path));

    for (final dir in subdirs) {
      final dirName = path.basename(dir.path);
      final dartFiles = dir
          .listSync()
          .whereType<File>()
          .where(
            (f) =>
                f.path.endsWith('.dart') &&
                !path.basename(f.path).startsWith('_'),
          )
          .toList()
        ..sort((a, b) => a.path.compareTo(b.path));

      for (final file in dartFiles) {
        final fileName = path.basename(file.path);
        buffer.writeln("export '$layerName/$dirName/$fileName';");
      }
    }
  }

  void _writeBarrel(String barrelPath, String content, {bool force = false}) {
    if (content.trim().endsWith('BY HAND')) {
      // No actual exports, skip
      return;
    }

    if (File(barrelPath).existsSync() && !force) {
      Console.warning(
        'Barrel file exists: $barrelPath (use --force to overwrite)',
      );
      return;
    }

    YoUtils.writeFile(barrelPath, content);
  }
}
